name: promotion_overlay_foundation_example
description: Testbed for the promotion_overlay_foundation implementation.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-97.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  promotion_overlay_foundation:
    # When depending on this package from a real application you should use:
    #   promotion_overlay_foundation: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  promotion_overlay_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true