name: promotion_overlay_foundation
description: iOS and macOS implementation of the promotion_overlay plugin.
repository: https://github.com/psycatgames/promotion_overlay_foundation
version: 1.0.0

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: promotion_overlay
    platforms:
      ios:
        pluginClass: PromotionOverlayPlugin
        dartPluginClass: PromotionOverlayFoundation
        sharedDarwinSource: true
      macos:
        pluginClass: PromotionOverlayPlugin
        dartPluginClass: PromotionOverlayFoundation
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  promotion_overlay_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.1.6

topics:
  - app-store